name: CI checks

on:
  push:
    branches: [ "main", "dev/hyl" ]
  pull_request:
    branches: [ "main", "dev/hyl" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: check
        run:
          cargo check --all-features
      - name: fmt-check
        run:
          cargo fmt --all -- --check
      - name: Clippy
        run:
          cargo check --all-features
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
